apiVersion: v1
kind: Pod
metadata:
  labels:
    component: web
  name: client-pod
spec:
  containers:
    - image: stephengrider/multi-client
      name: client
      ports:
        - containerPort: 3000